In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)

In [4]:
RAW_DATA_PATH = Path("../data/raw")

SALES_PATH = RAW_DATA_PATH / "Sales_snapshot_data"
INVENTORY_PATH = RAW_DATA_PATH / "Inventory_snapshot_data"
MASTER_PATH = RAW_DATA_PATH / "MasterData"

In [5]:
print("Raw:", RAW_DATA_PATH.exists())
print("Sales:", SALES_PATH.exists())
print("Inventory:", INVENTORY_PATH.exists())
print("Master:", MASTER_PATH.exists())

Raw: True
Sales: True
Inventory: True
Master: True

In [6]:
sales_files = sorted(SALES_PATH.glob("*.xlsx"))

print(f"Number of sales files: {len(sales_files)}")

for file in sales_files:
    print(file.name)

Number of sales files: 19
TT T01-2022_split_1.xlsx
TT T01-2023_split_1.xlsx
TT T02-2022_split_1.xlsx
TT T02-2023_split_1.xlsx
TT T03-2022_split_1.xlsx
TT T03-2023_split_1.xlsx
TT T04-2022_split_1.xlsx
TT T04-2023_split_1.xlsx
TT T05-2022_split_1.xlsx
TT T05-2023_split_1.xlsx
TT T06-2022_split_1.xlsx
TT T06-2023_split_1.xlsx
TT T07-2022_split_1.xlsx
TT T07-2023_split_1.xlsx
TT T08-2022_split_1.xlsx
TT T09-2022_split_1.xlsx
TT T10-2022_split_1.xlsx
TT T11-2022_split_1.xlsx
TT T12-2022_split_1.xlsx

In [7]:
sample_sales = pd.read_excel(sales_files[0])

sample_sales.head()

,month,week,site,branch_id,channel_id,distribution_channel,distribution_channel_code,sold_quantity,cost_price,net_price,customer_id,product_id
0,2022001,202201,1800,1800,Online,Online,ZF2,1,495720,729000,9847d4248,d77fdd34a14845db97837e059b0aca00TRG42
1,2022001,202204,1116,1100,CHTT,Bán lẻ,FP,1,221000,325000,2384aef55,e485c0ab7b9b470cbddb80ea7367e734DEN40
2,2022001,202201,1134,1100,CHTT,Bán lẻ,FP,1,255000,375000,20c3e0442,ac88f78262ee4b589bc93b106b67af1dDEN42
3,2022001,202204,1612,1600,CHTT,Bán lẻ,FP,1,258400,380000,e8b42ff8f,920641c624934c4a8695347737f8f59dDEN35
4,2022001,202202,1511,1500,CHTT,Bán lẻ,FP,1,272000,400000,b8d51499a,6764565f4bb141138af7d9cbf0905d0dHOL33

In [8]:
sample_sales.shape

(81893, 12)

In [9]:
sample_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 81893 entries, 0 to 81892
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      81893 non-null  int64
 1   week                       81893 non-null  int64
 2   site                       81893 non-null  int64
 3   branch_id                  81893 non-null  int64
 4   channel_id                 81893 non-null  str
 5   distribution_channel       81893 non-null  str
 6   distribution_channel_code  81893 non-null  str
 7   sold_quantity              81893 non-null  int64
 8   cost_price                 81893 non-null  int64
 9   net_price                  81893 non-null  int64
 10  customer_id                81893 non-null  str
 11  product_id                 81893 non-null  str
dtypes: int64(7), str(5)
memory usage: 7.5 MB

In [10]:
sample_sales.columns.tolist()

['month',
 'week',
 'site',
 'branch_id',
 'channel_id',
 'distribution_channel',
 'distribution_channel_code',
 'sold_quantity',
 'cost_price',
 'net_price',
 'customer_id',
 'product_id']

In [11]:
sample_sales.isnull().sum()

month                        0
week                         0
site                         0
branch_id                    0
channel_id                   0
distribution_channel         0
distribution_channel_code    0
sold_quantity                0
cost_price                   0
net_price                    0
customer_id                  0
product_id                   0
dtype: int64

In [13]:
duplicate_count = sample_sales.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 867

Detect
  ↓
Investigate
  ↓
Understand
  ↓
Decide
  ↓
Clean

In [14]:
duplicates = sample_sales[
    sample_sales.duplicated(keep=False)
].sort_values(
    by=sample_sales.columns.tolist()
)

duplicates.head(20)

,month,week,site,branch_id,channel_id,distribution_channel,distribution_channel_code,sold_quantity,cost_price,net_price,customer_id,product_id
23017,2022001,202153,1101,1100,CHTT,Bán lẻ,FP,2,40800,60000,dd5a95cfa,398063140c7244ebab2ffa9f904e5a58DEN25
25311,2022001,202153,1101,1100,CHTT,Bán lẻ,FP,2,40800,60000,dd5a95cfa,398063140c7244ebab2ffa9f904e5a58DEN25
42972,2022001,202153,1103,1100,CHTT,Bán lẻ,FP,1,65280,96000,8a6174afa,4e9edf53cb984d0f94f8a0e1a3230fe4XAM39
60133,2022001,202153,1103,1100,CHTT,Bán lẻ,FP,1,65280,96000,8a6174afa,4e9edf53cb984d0f94f8a0e1a3230fe4XAM39
31162,2022001,202153,1120,1100,CHTT,Bán lẻ,FP,1,163200,240000,840519b59,b7426a7cffaa4a2886524339fbea9c64NAU40
35838,2022001,202153,1120,1100,CHTT,Bán lẻ,FP,1,163200,240000,840519b59,b7426a7cffaa4a2886524339fbea9c64NAU40
21616,2022001,202153,1136,1100,CHTT,Bán lẻ,FP,1,23800,35000,bc07ddb8b,4e3a6211c18049c8b9822d2b20cc1186KEM25
79631,2022001,202153,1136,1100,CHTT,Bán lẻ,FP,1,23800,35000,bc07ddb8b,4e3a6211c18049c8b9822d2b20cc1186KEM25
24379,2022001,202153,1144,1100,CHTT,Bán lẻ,FP,1,98600,145000,beead8b7f,8832d6df536f4c569eb799f440097a92DEN36
27231,2022001,202153,1144,1100,CHTT,Bán lẻ,FP,1,98600,145000,beead8b7f,8832d6df536f4c569eb799f440097a92DEN36
26246,2022001,202153,1169,1100,CHTT,Bán lẻ,FP,1,115600,170000,af0c5a86c,482f5945d9e94b00b6a81831701dee28DOD37
68272,2022001,202153,1169,1100,CHTT,Bán lẻ,FP,1,115600,170000,af0c5a86c,482f5945d9e94b00b6a81831701dee28DOD37
40198,2022001,202153,1402,1400,CHTT,Bán lẻ,FP,1,285600,420000,45b034593,13761ce2d2b84db8a1663be845d427eeXNH39
41344,2022001,202153,1402,1400,CHTT,Bán lẻ,FP,1,285600,420000,45b034593,13761ce2d2b84db8a1663be845d427eeXNH39
31214,2022001,202153,1503,1500,CHTT,Bán lẻ,FP,1,20400,30000,dfa3b8845,5b04cc6ec54c4fa2bd805180e53c325dDEN25
66174,2022001,202153,1503,1500,CHTT,Bán lẻ,FP,1,20400,30000,dfa3b8845,5b04cc6ec54c4fa2bd805180e53c325dDEN25
39522,2022001,202153,1513,1500,CHTT,Bán lẻ,FP,1,316200,465000,3ec77a1f4,e68e38da56a548439fe75f4faa849051DEN42
40586,2022001,202153,1513,1500,CHTT,Bán lẻ,FP,1,316200,465000,3ec77a1f4,e68e38da56a548439fe75f4faa849051DEN42
8264,2022001,202201,1100,1100,TGPP,Phát sinh,ZF2,1,81600,90000,226aefff7,653d00a961b249ada7fcbbd1092597b0XDG30
29752,2022001,202201,1100,1100,TGPP,Phát sinh,ZF2,1,81600,90000,226aefff7,653d00a961b249ada7fcbbd1092597b0XDG30

In [15]:
sample_sales.describe()

,month,week,site,branch_id,sold_quantity,cost_price,net_price
count,81893.0,81893.000000,81893.000000,81893.000000,81893.000000,8.189300e+04,8.189300e+04
mean,2022001.0,202199.951498,1297.232144,1276.405798,1.177842,2.623984e+05,3.614603e+05
std,0.0,11.567973,216.303954,222.938224,2.185908,4.374125e+05,5.326683e+05
min,2022001.0,202153.000000,1100.000000,1100.000000,-5.000000,-3.226600e+06,-3.796000e+06
25%,2022001.0,202202.000000,1123.000000,1100.000000,1.000000,1.156000e+05,1.500000e+05
50%,2022001.0,202203.000000,1169.000000,1100.000000,1.000000,1.972000e+05,2.850000e+05
75%,2022001.0,202204.000000,1508.000000,1500.000000,1.000000,3.060000e+05,4.350000e+05
max,2022001.0,202205.000000,2001.000000,2000.000000,150.000000,4.646304e+07,5.440155e+07

In [16]:
sample_sales[
    ["sold_quantity", "cost_price", "net_price"]
].describe()

       sold_quantity    cost_price     net_price
count   81893.000000  8.189300e+04  8.189300e+04
mean        1.177842  2.623984e+05  3.614603e+05
std         2.185908  4.374125e+05  5.326683e+05
min        -5.000000 -3.226600e+06 -3.796000e+06
25%         1.000000  1.156000e+05  1.500000e+05
50%         1.000000  1.972000e+05  2.850000e+05
75%         1.000000  3.060000e+05  4.350000e+05
max       150.000000  4.646304e+07  5.440155e+07

In [17]:
for col in ["sold_quantity", "cost_price", "net_price"]:
    print(f"\n--- {col} ---")
    print("Min:", sample_sales[col].min())
    print("Max:", sample_sales[col].max())
    print("Zero:", (sample_sales[col] == 0).sum())
    print("Negative:", (sample_sales[col] < 0).sum())

--- sold_quantity ---
Min: -5
Max: 150
Zero: 0
Negative: 2801

--- cost_price ---
Min: -3226600
Max: 46463040
Zero: 0
Negative: 2801

--- net_price ---
Min: -3796000
Max: 54401553
Zero: 174
Negative: 2760

In [18]:
sample_sales["distribution_channel"].value_counts(dropna=False)

distribution_channel
Bán lẻ       72722
Phát sinh     5488
Online        1858
Siêu thị       881
Bán sỉ         523
-              234
Hợp đồng       187
Name: count, dtype: int64

In [19]:
sample_sales["channel_id"].value_counts(dropna=False)

channel_id
CHTT      73479
TGPP       5675
Online     1858
ST          881
Name: count, dtype: int64

In [20]:
for file in sales_files:
    df = pd.read_excel(file)

    print(
        file.name,
        df.shape,
        len(df.columns)
    )

TT T01-2022_split_1.xlsx (81893, 12) 12
TT T01-2023_split_1.xlsx (57914, 12) 12
TT T02-2022_split_1.xlsx (37324, 12) 12
TT T02-2023_split_1.xlsx (25204, 12) 12
TT T03-2022_split_1.xlsx (29228, 12) 12
TT T03-2023_split_1.xlsx (29440, 12) 12
TT T04-2022_split_1.xlsx (49269, 12) 12
TT T04-2023_split_1.xlsx (39724, 12) 12
TT T05-2022_split_1.xlsx (37263, 12) 12
TT T05-2023_split_1.xlsx (28744, 12) 12
TT T06-2022_split_1.xlsx (38460, 12) 12
TT T06-2023_split_1.xlsx (29772, 12) 12
TT T07-2022_split_1.xlsx (55288, 12) 12
TT T07-2023_split_1.xlsx (42181, 12) 12
TT T08-2022_split_1.xlsx (65296, 12) 12
TT T09-2022_split_1.xlsx (38301, 12) 12
TT T10-2022_split_1.xlsx (36652, 12) 12
TT T11-2022_split_1.xlsx (49789, 12) 12
TT T12-2022_split_1.xlsx (60224, 12) 12

In [21]:
base_columns = set(
    pd.read_excel(sales_files[0], nrows=0).columns
)

for file in sales_files[1:]:
    current_columns = set(
        pd.read_excel(file, nrows=0).columns
    )

    if current_columns != base_columns:
        print("Different schema:", file.name)

In [22]:
sales_list = []

for file in sales_files:

    print("Reading:", file.name)

    df = pd.read_excel(file)

    df["source_file"] = file.name

    sales_list.append(df)

sales = pd.concat(
    sales_list,
    ignore_index=True
)

Reading: TT T01-2022_split_1.xlsx
Reading: TT T01-2023_split_1.xlsx
Reading: TT T02-2022_split_1.xlsx
Reading: TT T02-2023_split_1.xlsx
Reading: TT T03-2022_split_1.xlsx
Reading: TT T03-2023_split_1.xlsx
Reading: TT T04-2022_split_1.xlsx
Reading: TT T04-2023_split_1.xlsx
Reading: TT T05-2022_split_1.xlsx
Reading: TT T05-2023_split_1.xlsx
Reading: TT T06-2022_split_1.xlsx
Reading: TT T06-2023_split_1.xlsx
Reading: TT T07-2022_split_1.xlsx
Reading: TT T07-2023_split_1.xlsx
Reading: TT T08-2022_split_1.xlsx
Reading: TT T09-2022_split_1.xlsx
Reading: TT T10-2022_split_1.xlsx
Reading: TT T11-2022_split_1.xlsx
Reading: TT T12-2022_split_1.xlsx

In [23]:
sales.shape

(831966, 13)

In [24]:
sales.head()

,month,week,site,branch_id,channel_id,distribution_channel,distribution_channel_code,sold_quantity,cost_price,net_price,customer_id,product_id,source_file
0,2022001,202201,1800,1800,Online,Online,ZF2,1,495720,729000,9847d4248,d77fdd34a14845db97837e059b0aca00TRG42,TT T01-2022_split_1.xlsx
1,2022001,202204,1116,1100,CHTT,Bán lẻ,FP,1,221000,325000,2384aef55,e485c0ab7b9b470cbddb80ea7367e734DEN40,TT T01-2022_split_1.xlsx
2,2022001,202201,1134,1100,CHTT,Bán lẻ,FP,1,255000,375000,20c3e0442,ac88f78262ee4b589bc93b106b67af1dDEN42,TT T01-2022_split_1.xlsx
3,2022001,202204,1612,1600,CHTT,Bán lẻ,FP,1,258400,380000,e8b42ff8f,920641c624934c4a8695347737f8f59dDEN35,TT T01-2022_split_1.xlsx
4,2022001,202202,1511,1500,CHTT,Bán lẻ,FP,1,272000,400000,b8d51499a,6764565f4bb141138af7d9cbf0905d0dHOL33,TT T01-2022_split_1.xlsx

In [25]:
sales.tail()

,month,week,site,branch_id,channel_id,distribution_channel,distribution_channel_code,sold_quantity,cost_price,net_price,customer_id,product_id,source_file
831961,2022012,202248,1100,1100,TGPP,Hợp đồng,ZF1,2,1053530,1177476,2d22168a7,1f6d028054a243beb1d014bc060e2cacDEN44,TT T12-2022_split_1.xlsx
831962,2022012,202250,1100,1100,TGPP,Hợp đồng,ZF1,4,854576,942546,527c67310,b231b73faed54fc49508a6f6700fcb25HOG38,TT T12-2022_split_1.xlsx
831963,2022012,202251,1214,1200,CHTT,Bán lẻ,FP,1,534109,785000,90a132d97,ef228e1c67564e4e90def4572446b047DEN43,TT T12-2022_split_1.xlsx
831964,2022012,202251,1148,1100,CHTT,Bán lẻ,FP,1,513412,755000,0475c4442,bc1896cc99bb44e395015b5e3646005aDEN41,TT T12-2022_split_1.xlsx
831965,2022012,202248,1100,1100,TGPP,Hợp đồng,ZF1,1,123513,141676,245e6677b,275171c2a6e24afb803a36d4cd87ef46DEN43,TT T12-2022_split_1.xlsx

In [26]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 831966 entries, 0 to 831965
Data columns (total 13 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   month                      831966 non-null  int64
 1   week                       831966 non-null  int64
 2   site                       831966 non-null  int64
 3   branch_id                  831966 non-null  int64
 4   channel_id                 831966 non-null  str
 5   distribution_channel       831966 non-null  str
 6   distribution_channel_code  831966 non-null  str
 7   sold_quantity              831966 non-null  int64
 8   cost_price                 831966 non-null  int64
 9   net_price                  831966 non-null  int64
 10  customer_id                831965 non-null  str
 11  product_id                 831966 non-null  str
 12  source_file                831966 non-null  str
dtypes: int64(7), str(6)
memory usage: 82.5 MB

In [28]:
sales["source_file"].value_counts()

source_file
TT T01-2022_split_1.xlsx    81893
TT T08-2022_split_1.xlsx    65296
TT T12-2022_split_1.xlsx    60224
TT T01-2023_split_1.xlsx    57914
TT T07-2022_split_1.xlsx    55288
TT T11-2022_split_1.xlsx    49789
TT T04-2022_split_1.xlsx    49269
TT T07-2023_split_1.xlsx    42181
TT T04-2023_split_1.xlsx    39724
TT T06-2022_split_1.xlsx    38460
TT T09-2022_split_1.xlsx    38301
TT T02-2022_split_1.xlsx    37324
TT T05-2022_split_1.xlsx    37263
TT T10-2022_split_1.xlsx    36652
TT T06-2023_split_1.xlsx    29772
TT T03-2023_split_1.xlsx    29440
TT T03-2022_split_1.xlsx    29228
TT T05-2023_split_1.xlsx    28744
TT T02-2023_split_1.xlsx    25204
Name: count, dtype: int64

In [27]:
sales.groupby("source_file").size()

source_file
TT T01-2022_split_1.xlsx    81893
TT T01-2023_split_1.xlsx    57914
TT T02-2022_split_1.xlsx    37324
TT T02-2023_split_1.xlsx    25204
TT T03-2022_split_1.xlsx    29228
TT T03-2023_split_1.xlsx    29440
TT T04-2022_split_1.xlsx    49269
TT T04-2023_split_1.xlsx    39724
TT T05-2022_split_1.xlsx    37263
TT T05-2023_split_1.xlsx    28744
TT T06-2022_split_1.xlsx    38460
TT T06-2023_split_1.xlsx    29772
TT T07-2022_split_1.xlsx    55288
TT T07-2023_split_1.xlsx    42181
TT T08-2022_split_1.xlsx    65296
TT T09-2022_split_1.xlsx    38301
TT T10-2022_split_1.xlsx    36652
TT T11-2022_split_1.xlsx    49789
TT T12-2022_split_1.xlsx    60224
dtype: int64

In [29]:
quality_report = pd.DataFrame({
    "dtype": sales.dtypes.astype(str),
    "rows": len(sales),
    "missing": sales.isnull().sum(),
    "missing_pct": (
        sales.isnull().mean() * 100
    ).round(2),
    "unique": sales.nunique()
})

quality_report

                           dtype    rows  missing  missing_pct  unique
month                      int64  831966        0          0.0      19
week                       int64  831966        0          0.0      85
site                       int64  831966        0          0.0     227
branch_id                  int64  831966        0          0.0       8
channel_id                   str  831966        0          0.0       5
distribution_channel         str  831966        0          0.0       7
distribution_channel_code    str  831966        0          0.0       9
sold_quantity              int64  831966        0          0.0     124
cost_price                 int64  831966        0          0.0    6314
net_price                  int64  831966        0          0.0   25763
customer_id                  str  831966        1          0.0    1173
product_id                   str  831966        0          0.0   30367
source_file                  str  831966        0          0.0      19